/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.utfpr.academia.view;

import br.utfpr.academia.controller.UsuarioController;
import br.utfpr.academia.model.Usuario;
import br.utfpr.academia.service.ValidacaoService;
import javax.swing.JOptionPane;

/**
 *
 * @Author Isabely Aparecedia Gomes da Costa RA: 2337541
 * @Author Luana Monteiro Ferreira
 */
public class FormCriarConta extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCriarConta.class.getName());

    /**
     * Creates new form FormCriarConta
     */
    public FormCriarConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        LbEmailInstitucional = new javax.swing.JLabel();
        InputEmailInstitucional = new javax.swing.JTextField();
        LbSenha = new javax.swing.JLabel();
        InputSenha = new javax.swing.JPasswordField();
        LbConfSenha = new javax.swing.JLabel();
        InputConfSenha = new javax.swing.JPasswordField();
        LbNome = new javax.swing.JLabel();
        InputNome = new javax.swing.JTextField();
        LbCurso = new javax.swing.JLabel();
        SelectCurso = new javax.swing.JComboBox<>();
        LbSemestre = new javax.swing.JLabel();
        SelectSemestre = new javax.swing.JComboBox<>();
        LbPergSecreta = new javax.swing.JLabel();
        InputPergSecreta = new javax.swing.JComboBox<>();
        LbRespSecreta = new javax.swing.JLabel();
        InputRespSecreta = new javax.swing.JTextField();
        btCriarConta = new javax.swing.JButton();
        LbVoltar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Titulo.setText("Crie sua conta!");

        LbEmailInstitucional.setText("Email Institucional");

        InputEmailInstitucional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmailInstitucionalActionPerformed(evt);
            }
        });

        LbSenha.setText("Senha");

        InputSenha.setToolTipText("");
        InputSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputSenhaActionPerformed(evt);
            }
        });

        LbConfSenha.setText("Confirme sua senha ");

        InputConfSenha.setToolTipText("");
        InputConfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputConfSenhaActionPerformed(evt);
            }
        });

        LbNome.setText("Nome completo");

        InputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNomeActionPerformed(evt);
            }
        });

        LbCurso.setText("Curso");

        SelectCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciência da Computação", "Engenharia de Software", "Engenharia Elétrica", "Administração" }));
        SelectCurso.setPreferredSize(new java.awt.Dimension(220, 22));

        LbSemestre.setText("Semestre ");

        SelectSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        SelectSemestre.setPreferredSize(new java.awt.Dimension(110, 22));

        LbPergSecreta.setText("Pergunta Secreta");

        InputPergSecreta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qual o nome do seu primeiro pet?", "Qual sua cidade natal?", "Qual seu filme favorito?" }));
        InputPergSecreta.setMinimumSize(new java.awt.Dimension(220, 22));
        InputPergSecreta.setPreferredSize(new java.awt.Dimension(220, 22));
        InputPergSecreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPergSecretaActionPerformed(evt);
            }
        });

        LbRespSecreta.setText("Resposta secreta");

        InputRespSecreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputRespSecretaActionPerformed(evt);
            }
        });

        btCriarConta.setText("Criar");
        btCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarContaActionPerformed(evt);
            }
        });

        LbVoltar.setText("Já tem uma conta? Entrar");
        LbVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LbNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InputConfSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(LbConfSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InputNome, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbRespSecreta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(LbPergSecreta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(InputPergSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(InputRespSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(InputSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                            .addComponent(LbSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(57, 57, 57)
                                        .addComponent(SelectSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(InputEmailInstitucional)
                                            .addComponent(LbEmailInstitucional, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LbSemestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SelectCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LbCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(LbVoltar))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputEmailInstitucional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LbEmailInstitucional, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbPergSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputPergSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbRespSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputRespSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btCriarConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LbVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputEmailInstitucionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmailInstitucionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEmailInstitucionalActionPerformed

    private void InputSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputSenhaActionPerformed

    private void btCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarContaActionPerformed
        String email = InputEmailInstitucional.getText().trim();
        String senha = new String(InputSenha.getPassword()).trim();
        String confirmarSenha = new String(InputConfSenha.getPassword()).trim();
        String nome = InputNome.getText().trim();
        String curso = (String) SelectCurso.getSelectedItem();
        String semestre = (String) SelectSemestre.getSelectedItem();
        String perguntaSecreta = (String) InputPergSecreta.getSelectedItem();
        String respostaSecreta = InputRespSecreta.getText().trim();

        if (email.isEmpty()
                || senha.isEmpty()
                || confirmarSenha.isEmpty()
                || nome.isEmpty()
                || curso == null || curso.isEmpty()
                || semestre == null || semestre.isEmpty()
                || perguntaSecreta == null || perguntaSecreta.isEmpty()
                || respostaSecreta.isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Todos os campos são obrigatórios.",
                    "Campos obrigatórios",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validação: senhas conferem?
        if (!ValidacaoService.senhasConferem(senha, confirmarSenha)) {
            JOptionPane.showMessageDialog(this,
                    "As senhas não conferem.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Usuario usuario = new Usuario();
            usuario.setEmail(email);
            usuario.setSenha(senha);
            usuario.setNome(nome);
            usuario.setCurso(curso);
            usuario.setSemestre(Integer.parseInt(semestre)); // Cuidado aqui, veja nota abaixo!
            usuario.setPerguntaSecreta(perguntaSecreta);
            usuario.setRespostaSecreta(respostaSecreta);

            // Se tiver mais campos como interesses, perfil público etc., adicione conforme necessário
            new UsuarioController().cadastrarUsuario(usuario);
            JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");

            FormPrincipal novaTela = new FormPrincipal();
            novaTela.setSize(this.getSize());        
            novaTela.setLocation(this.getLocation()); 
            novaTela.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro no Cadastro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCriarContaActionPerformed

    private void InputConfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputConfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputConfSenhaActionPerformed

    private void InputPergSecretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPergSecretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPergSecretaActionPerformed

    private void InputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNomeActionPerformed

    private void InputRespSecretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputRespSecretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputRespSecretaActionPerformed

    private void LbVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbVoltarMouseClicked
        FormPrincipal novaTela = new FormPrincipal();
        novaTela.setSize(this.getSize());        
        novaTela.setLocation(this.getLocation()); 
        novaTela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbVoltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCriarConta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField InputConfSenha;
    private javax.swing.JTextField InputEmailInstitucional;
    private javax.swing.JTextField InputNome;
    private javax.swing.JComboBox<String> InputPergSecreta;
    private javax.swing.JTextField InputRespSecreta;
    private javax.swing.JPasswordField InputSenha;
    private javax.swing.JLabel LbConfSenha;
    private javax.swing.JLabel LbCurso;
    private javax.swing.JLabel LbEmailInstitucional;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbPergSecreta;
    private javax.swing.JLabel LbRespSecreta;
    private javax.swing.JLabel LbSemestre;
    private javax.swing.JLabel LbSenha;
    private javax.swing.JLabel LbVoltar;
    private javax.swing.JComboBox<String> SelectCurso;
    private javax.swing.JComboBox<String> SelectSemestre;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btCriarConta;
    // End of variables declaration//GEN-END:variables
}
