/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.utfpr.academia.view;

import br.utfpr.academia.controller.LoginController;
import javax.swing.JOptionPane;

/**
 *
 * @author luism
 */
public class FormRecuperarSenha extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRecuperarSenha.class.getName());

    /**
     * Creates new form FormRecuperarSenha
     */
    public FormRecuperarSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        LbEmail = new javax.swing.JLabel();
        InputEmail = new javax.swing.JTextField();
        LbFraseSecreta = new javax.swing.JLabel();
        InputFraseSecreta = new javax.swing.JTextField();
        LbVoltarLogin = new javax.swing.JLabel();
        btRecuperar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Titulo.setText("Recuperar Senha!");

        LbEmail.setText("Email");

        InputEmail.setPreferredSize(new java.awt.Dimension(265, 22));
        InputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmailActionPerformed(evt);
            }
        });

        LbFraseSecreta.setText("Frase Secreta");

        InputFraseSecreta.setPreferredSize(new java.awt.Dimension(265, 22));
        InputFraseSecreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFraseSecretaActionPerformed(evt);
            }
        });

        LbVoltarLogin.setText("Lembrou da senha? Entrar");
        LbVoltarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbVoltarLoginMouseClicked(evt);
            }
        });

        btRecuperar.setText("Recuperar");
        btRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRecuperarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(InputFraseSecreta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbFraseSecreta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbVoltarLogin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btRecuperar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InputEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Titulo)
                .addGap(40, 40, 40)
                .addComponent(LbEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(LbFraseSecreta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputFraseSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(LbVoltarLogin)
                .addGap(20, 20, 20)
                .addComponent(btRecuperar)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRecuperarActionPerformed
        String email = InputEmail.getText().trim();
        String fraseSecreta = InputFraseSecreta.getText().trim();

        if (email.isEmpty() || fraseSecreta.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Email e frase secreta são obrigatórios.",
                    "Campos obrigatórios",
                    JOptionPane.WARNING_MESSAGE);
            return; // Sai do método sem tentar autenticar
        }

        try {
            String senha = new LoginController().recuperarSenha(email, fraseSecreta);
            System.out.println(senha);

            // Se chegou aqui, deu certo!
            JOptionPane.showMessageDialog(this,
                    "Sua senha é: " + senha,
                    "Recuperar Senha",
                    JOptionPane.INFORMATION_MESSAGE);

            FormPrincipal novaTela = new FormPrincipal();
            novaTela.setSize(this.getSize());        // <-- Mesmo tamanho da tela anterior
            novaTela.setLocation(this.getLocation()); // <-- Mesma posição (opcional)
            novaTela.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Erro no Login",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btRecuperarActionPerformed

    private void LbVoltarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbVoltarLoginMouseClicked
        FormPrincipal novaTela = new FormPrincipal();
        novaTela.setSize(this.getSize());        // <-- Mesmo tamanho da tela anterior
        novaTela.setLocation(this.getLocation()); // <-- Mesma posição (opcional)
        novaTela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbVoltarLoginMouseClicked

    private void InputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEmailActionPerformed

    private void InputFraseSecretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFraseSecretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFraseSecretaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormRecuperarSenha().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputEmail;
    private javax.swing.JTextField InputFraseSecreta;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbFraseSecreta;
    private javax.swing.JLabel LbVoltarLogin;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btRecuperar;
    // End of variables declaration//GEN-END:variables
}
