/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.utfpr.academia.view;

import br.utfpr.academia.controller.UsuarioController;
import br.utfpr.academia.model.Usuario;
import br.utfpr.academia.session.SessaoUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author luism
 */
public class FormPerfil extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPerfil.class.getName());

    /**
     * Creates new form FormPerfil
     */
    public FormPerfil() {
        initComponents();
        carregarDadosUsuario();
    }

    private void carregarDadosUsuario() {
        try {
            Usuario usuarioLogado = SessaoUsuario.getInstance().getUsuarioLogado();
            if (usuarioLogado == null) {
                throw new Exception("Sessão expirada! Faça login novamente.");
            }
            Usuario usuario = new UsuarioController().buscarUsuarioPorId(usuarioLogado.getId());
            if (usuario == null) {
                JOptionPane.showMessageDialog(this, "Usuário não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
                // Redireciona para tela de login:
                FormPrincipal login = new FormPrincipal();
                login.setVisible(true);
                this.dispose();
                return;
            }

            // Preenche os campos:
            InputNomeCompleto.setText(usuario.getNome());
            InputCurso.setText(usuario.getCurso());
            InputSemestre.setText(String.valueOf(usuario.getSemestre()));
            InputPerguntaSecreta.setText(usuario.getPerguntaSecreta());
            InputRespostaSecreta.setText(usuario.getRespostaSecreta());

            InputNomeCompleto.setEditable(false);
            InputCurso.setEditable(false);
            InputSemestre.setEditable(false);
            InputPerguntaSecreta.setEditable(false);
            InputRespostaSecreta.setEditable(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            FormPrincipal login = new FormPrincipal();
            login.setVisible(true);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        LbNomeCompleto = new javax.swing.JLabel();
        InputNomeCompleto = new javax.swing.JTextField();
        LbCurso = new javax.swing.JLabel();
        InputCurso = new javax.swing.JTextField();
        LbSemestre = new javax.swing.JLabel();
        InputSemestre = new javax.swing.JTextField();
        LbPerguntaSecreta = new javax.swing.JLabel();
        InputPerguntaSecreta = new javax.swing.JTextField();
        LbRespostaSecreta = new javax.swing.JLabel();
        InputRespostaSecreta = new javax.swing.JTextField();
        BtVoltar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Titulo.setText("Meu Perfil");

        LbNomeCompleto.setText("Nome Completo");

        InputNomeCompleto.setEditable(false);
        InputNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNomeCompletoActionPerformed(evt);
            }
        });

        LbCurso.setText("Curso");

        InputCurso.setEditable(false);
        InputCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCursoActionPerformed(evt);
            }
        });

        LbSemestre.setText("Semestre");

        InputSemestre.setEditable(false);
        InputSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputSemestreActionPerformed(evt);
            }
        });

        LbPerguntaSecreta.setText("Pergunta Secreta");

        InputPerguntaSecreta.setEditable(false);
        InputPerguntaSecreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPerguntaSecretaActionPerformed(evt);
            }
        });

        LbRespostaSecreta.setText("Resposta secreta");

        InputRespostaSecreta.setEditable(false);
        InputRespostaSecreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputRespostaSecretaActionPerformed(evt);
            }
        });

        BtVoltar.setText("Voltar");
        BtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LbCurso)
                            .addComponent(InputCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(LbNomeCompleto)
                            .addComponent(InputNomeCompleto)
                            .addComponent(LbSemestre)
                            .addComponent(InputSemestre, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(LbPerguntaSecreta)
                            .addComponent(InputPerguntaSecreta, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(LbRespostaSecreta)
                            .addComponent(InputRespostaSecreta, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(BtVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Titulo)
                .addGap(15, 15, 15)
                .addComponent(LbNomeCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(LbCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(LbSemestre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(LbPerguntaSecreta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputPerguntaSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(LbRespostaSecreta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputRespostaSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(BtVoltar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNomeCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNomeCompletoActionPerformed

    private void InputCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCursoActionPerformed

    private void InputSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputSemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputSemestreActionPerformed

    private void InputPerguntaSecretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPerguntaSecretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPerguntaSecretaActionPerformed

    private void InputRespostaSecretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputRespostaSecretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputRespostaSecretaActionPerformed

    private void BtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltarActionPerformed
        FormPublicacoes telaPub = new FormPublicacoes();
        telaPub.setSize(this.getSize());
        telaPub.setLocation(this.getLocation());
        telaPub.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPerfil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtVoltar;
    private javax.swing.JTextField InputCurso;
    private javax.swing.JTextField InputNomeCompleto;
    private javax.swing.JTextField InputPerguntaSecreta;
    private javax.swing.JTextField InputRespostaSecreta;
    private javax.swing.JTextField InputSemestre;
    private javax.swing.JLabel LbCurso;
    private javax.swing.JLabel LbNomeCompleto;
    private javax.swing.JLabel LbPerguntaSecreta;
    private javax.swing.JLabel LbRespostaSecreta;
    private javax.swing.JLabel LbSemestre;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
