/**
 * @version Product Version: Apache NetBeans IDE 15
 * @author Isabely Aparecedia Gomes da Costa RA: 2337541
 */

/*
 * Mais informações
 * Java: 21.0.4; Java HotSpot(TM) 64-Bit Server VM 21.0.4+8-LTS-274
 * Runtime: Java(TM) SE Runtime Environment 21.0.4+8-LTS-274
 * System: Windows 11 version 10.0 running on amd64; UTF-8; pt_BR (nb)
 */

 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.utfpr.academia.view;

import br.utfpr.academia.controller.LoginController;
import br.utfpr.academia.model.Usuario;
import javax.swing.JOptionPane;

public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Titulo = new javax.swing.JLabel();
        LbEmail = new javax.swing.JLabel();
        InputEmail = new javax.swing.JTextField();
        LbSenha = new javax.swing.JLabel();
        InputSenha = new javax.swing.JPasswordField();
        LbRecuperarSenha = new javax.swing.JLabel();
        btRelatorioPacientes = new javax.swing.JButton();
        LbCriarConta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Titulo.setText("Bem vindo ao Sistema!");

        LbEmail.setText("Email");

        InputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmailActionPerformed(evt);
            }
        });

        LbSenha.setText("Senha");

        InputSenha.setToolTipText("");
        InputSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputSenhaActionPerformed(evt);
            }
        });

        LbRecuperarSenha.setText("Esqueceu sua senha? Troque aqui!");
        LbRecuperarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbRecuperarSenhaMouseClicked(evt);
            }
        });

        btRelatorioPacientes.setText("Entrar");
        btRelatorioPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioPacientesActionPerformed(evt);
            }
        });

        LbCriarConta.setText("Não possui uma conta? Crie aqui!");
        LbCriarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCriarContaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(182, 182, 182)
                            .addComponent(Titulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(143, 143, 143)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LbCriarConta)
                                .addComponent(btRelatorioPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LbRecuperarSenha)
                        .addComponent(InputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Titulo)
                .addGap(40, 40, 40)
                .addComponent(LbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(InputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(LbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(InputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbRecuperarSenha)
                .addGap(15, 15, 15)
                .addComponent(btRelatorioPacientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LbCriarConta)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRelatorioPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioPacientesActionPerformed
        String email = InputEmail.getText().trim();
        String senha = new String(InputSenha.getPassword()).trim();

        if (email.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Email e senha são obrigatórios.",
                    "Campos obrigatórios",
                    JOptionPane.WARNING_MESSAGE);
            return; // Sai do método sem tentar autenticar
        }

        try {
            Usuario usuarioAutenticado = new LoginController().autenticar(email, senha);

            // Se chegou aqui, deu certo!
            JOptionPane.showMessageDialog(this,
                    "Login realizado com sucesso!",
                    "Bem-vindo(a)",
                    JOptionPane.INFORMATION_MESSAGE);

            FormPublicacoes novaTela = new FormPublicacoes();
            novaTela.setSize(this.getSize());        // <-- Mesmo tamanho da tela anterior
            novaTela.setLocation(this.getLocation()); // <-- Mesma posição (opcional)
            novaTela.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Erro no Login",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btRelatorioPacientesActionPerformed

    private void InputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEmailActionPerformed

    private void InputSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputSenhaActionPerformed

    private void LbCriarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCriarContaMouseClicked
        FormCriarConta novaTela = new FormCriarConta();
        novaTela.setSize(this.getSize());        // <-- Mesmo tamanho da tela anterior
        novaTela.setLocation(this.getLocation()); // <-- Mesma posição (opcional)
        novaTela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbCriarContaMouseClicked

    private void LbRecuperarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbRecuperarSenhaMouseClicked
        FormRecuperarSenha novaTela = new FormRecuperarSenha();
        novaTela.setSize(this.getSize());        // <-- Mesmo tamanho da tela anterior
        novaTela.setLocation(this.getLocation()); // <-- Mesma posição (opcional)
        novaTela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbRecuperarSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputEmail;
    private javax.swing.JPasswordField InputSenha;
    private javax.swing.JLabel LbCriarConta;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbRecuperarSenha;
    private javax.swing.JLabel LbSenha;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btRelatorioPacientes;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
